version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules